### ISSUE TITLE
[Home] Set default mealIdx

### ISSUE THREAD

**Issue by hhhello0507** [Team-B1ND/dodamdodam-ios#157]
- 현재는 -1로 설정 돼 있어 page indicator에도 표시되지 않는 현상 발생
- 기본값을 현재 시간에 따른 MealType으로 설정

**Comment by lkh0310kr** [comment]
수정:
오늘 저녁 급식 시간이 지났고 자정을 넘지 않았다면  '오늘의 아침' -> '내일의 급식'
